CREATE TABLE IF NOT EXISTS lesson_candidates (
  id TEXT PRIMARY KEY,
  session_id TEXT,
  moment_id TEXT,
  title TEXT,
  rule TEXT,
  lesson_type TEXT,
  raw_moment TEXT,
  rationale TEXT,
  cqs_score REAL,
  keywords TEXT,
  embedding TEXT,
  dedup_hash TEXT,
  extraction_model TEXT,
  extracted_at TEXT,
  confirmed_count INTEGER DEFAULT 0,
  confirmed_sessions TEXT,
  contradicted_by TEXT,
  superseded_by TEXT,
  validation_status TEXT DEFAULT 'promoted',
  validation_details TEXT,
  validated_at TEXT,
  reliability REAL DEFAULT 0.5,
  vector_indexed INTEGER DEFAULT 0,
  vector_score REAL DEFAULT 0.0
);
